const csp = {
  resourceDomains: [
    "https://cdn.jsdelivr.net",
    "https://fonts.googleapis.com",
    "https://fonts.gstatic.com",
    "https://tile.openstreetmap.org",
    "https://firms.modaps.eosdis.nasa.gov",
    "https://gibs.earthdata.nasa.gov",
    "https://server.arcgisonline.com",
    "data:",
    "blob:",
  ],
  connectDomains: [
    "https://cdn.jsdelivr.net",
    "https://harmony.earthdata.nasa.gov",
    "https://harmony.uat.earthdata.nasa.gov",
    "https://cmr.earthdata.nasa.gov",
    "https://cmr.uat.earthdata.nasa.gov",
    "https://api.giovanni.earthdata.nasa.gov",
    "https://api.giovanni.uat.earthdata.nasa.gov",
    "https://disc.gsfc.nasa.gov",
    "https://disc.uat.gsfc.nasa.gov",
    "https://firms.modaps.eosdis.nasa.gov",
    "https://gibs.earthdata.nasa.gov",
    "https://nominatim.openstreetmap.org",
    "https://server.arcgisonline.com",
    "https://4nad4npjmf.execute-api.us-east-1.amazonaws.com",
    "https://8weebb031a.execute-api.us-east-1.amazonaws.com",
    "https://u2u5qu332rhmxpiazjcqz6gkdm.appsync-api.us-east-1.amazonaws.com",
    "https://sjldutoe6c.execute-api.us-east-1.amazonaws.com",
    "https://lpo4uv7f0h.execute-api.us-east-1.amazonaws.com",
    "data:",
    "blob:",
    "https://nasa-gov.web-sandbox.oaiusercontent.com",
  ],
};

export default csp;
